# Generated By: Cursor (Claude Sonnet 4)
# Makefile for Astrophotography Data Management

# Include modular makefiles
include make/env.mk
include make/lint.mk

.DEFAULT_GOAL := help
.PHONY: help

# Python virtual environment
VENV_DIR ?= .venv
PYTHON := $(VENV_DIR)/bin/python
PIP := $(VENV_DIR)/bin/pip
UV := $(VENV_DIR)/bin/uv

# Colors for output
BLUE := \033[34m
GREEN := \033[32m
YELLOW := \033[33m
RESET := \033[0m

# Export common environment for all recipes
export PATH := $(CURDIR)/$(VENV_DIR)/bin:$(PATH)

help: ## Display this help message
	@echo "Astrophotography Data Management"
	@echo "==============================="
	@echo ""
	@echo "Available targets:"
	@echo ""
	@awk 'BEGIN {FS = ":.*?## "} /^[a-zA-Z_-]+:.*?## / {printf "  \033[36m%-15s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)